version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ecosphere-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecosphere
    volumes:
      - ecosphere_pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  ecosphere_pgdata:
